import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { GoogleAnalytics } from '@next/third-parties/google';
import { GoogleTagManager } from '@next/third-parties/google';

import { ColorModeProvider } from '@/contexts/ColorModeContext';
import { QueryContextProvider } from '@/contexts/QueryContext';

import Layout from '@/components/sharing/layout';
import { CssBaseline } from '@mui/material';

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import { GA_ID } from '@/constants/env';
import * as gtag from '@/utils/gtag';
// import { useRouter } from 'next/navigation';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const router = useRouter();
  // console.log('router:', router);
  // useEffect(() => {
  //   const handleRouteChange = (url: URL) => {
  //     gtag.pageview(url);
  //   };
  //   router.events.on('routeChangeComplete', handleRouteChange);
  //   return () => {
  //     router.events.off('routeChangeComplete', handleRouteChange);
  //   };
  // }, [router.events]);

  return (
    <QueryContextProvider>
      <html lang='en'>
        <ColorModeProvider>
          <body className={inter.className}>
            <CssBaseline />
            <Layout>{children}</Layout>
          </body>
        </ColorModeProvider>
        {GA_ID && <GoogleAnalytics gaId={GA_ID} />}
        {/* <GoogleTagManager gtmId={'GTM-5HLMMZ68'} /> */}
      </html>
    </QueryContextProvider>
  );
}
